---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
      platform: ubuntu


verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[aws-cloudwatch::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
      aws_cloudwatch:
        region: us-east-1
